Repository Likelion-13th-EGSBI/Likelion-13th-EGSBI-BE, pull requests merged in 2025-08, with the labels that each got.

#28 chore: gateway 패키지 경로 변경
  gateway/build.gradle
  gateway/src/main/java/life/eventory/gateway/GatewayApplication.java
  gateway/src/test/java/life/eventory/gateway/GatewayApplicationTests.java
Labels: refactor, backend

#29 refactor: eureka 패키지 그룹 변경
  eureka/build.gradle
  eureka/src/main/java/life/eventory/eureka/EurekaApplication.java
  eureka/src/main/java/life/eventory/eureka/config/SecurityConfig.java
  eureka/src/main/java/life/eventory/eureka/config/WebConfig.java
  eureka/src/test/java/life/eventory/eureka/EurekaApplicationTests.java
Labels: refactor, backend

#30 chore: event init
  event/.gitattributes
  event/.gitignore
  event/build.gradle
  event/gradle/wrapper/gradle-wrapper.jar
  event/gradle/wrapper/gradle-wrapper.properties
  event/gradlew
  event/gradlew.bat
  event/settings.gradle
  event/src/main/java/life/eventory/event/EventApplication.java
  event/src/main/resources/application.properties
  event/src/test/java/life/eventory/event/EventApplicationTests.java
Labels: backend

#31 feat: event 테이블 및 기초 기능 구현
  event/build.gradle
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/dto/EventDTO.java
  event/src/main/java/life/eventory/event/dto/NewEventDTO.java
  event/src/main/java/life/eventory/event/entity/Event.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
  event/src/main/resources/application.properties
Labels: feature, backend

#32 chore: gateway 및 보안 설정 추가
  gateway/build.gradle
  gateway/src/main/java/life/eventory/gateway/config/GatewayConfig.java
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
  gateway/src/main/resources/application.properties
Labels: backend

#34 chore: Create deploy-gateway.yml
  .github/workflows/deploy-gateway.yml
Labels: backend

#37 Create deploy-eureka.yml
  .github/workflows/deploy-eureka.yml
Labels: backend

#38 refactor: eureka 설정 변경
  eureka/build.gradle
  eureka/src/main/resources/application.properties
Labels: backend

#40 Chore: gateway event 라우트 경로 수정
  aggregator/.gitattributes
  aggregator/.gitignore
  aggregator/build.gradle
  aggregator/gradle/wrapper/gradle-wrapper.jar
  aggregator/gradle/wrapper/gradle-wrapper.properties
  aggregator/gradlew
  aggregator/gradlew.bat
  aggregator/settings.gradle
  aggregator/src/main/java/life/eventory/aggregator/AggregatorApplication.java
  aggregator/src/main/java/life/eventory/aggregator/config/AppConfig.java
  aggregator/src/main/java/life/eventory/aggregator/config/DynamicSwaggerConfig.java
  aggregator/src/main/resources/application.properties
  aggregator/src/test/java/life/eventory/aggregator/AggregatorApplicationTests.java
  event/src/main/resources/application.properties
  gateway/src/main/resources/application.properties
Labels: backend

#44 Create deploy-aggregator.yml
  .github/workflows/deploy-aggregator.yml
Labels: backend

#45 chore: gateway get 허용 수정
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
Labels: backend

#46 chore: gateway cors swagger 추가
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
Labels: backend

#50 chore: Event CORS 제거
  event/src/main/java/life/eventory/event/config/SecurityConfig.java
Labels: backend

#52 refactor: Swagger 관련 config 전부 수정
  event/src/main/java/life/eventory/event/config/SecurityConfig.java
  event/src/main/java/life/eventory/event/config/SwaggerConfig.java
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
Labels: refactor, backend

#53 Update deploy-event.yml
  .github/workflows/deploy-event.yml
Labels: refactor, backend

#54 chore: 프로젝트 파일 생성
  activity/.gitattributes
  activity/.gitignore
  activity/build.gradle
  activity/gradle/wrapper/gradle-wrapper.jar
  activity/gradle/wrapper/gradle-wrapper.properties
  activity/gradlew
  activity/gradlew.bat
  activity/settings.gradle
  activity/src/main/java/life/eventory/activity/ActivityApplication.java
  activity/src/main/resources/application.properties
  activity/src/test/java/life/eventory/activity/ActivityApplicationTests.java
Labels: backend, chore

#55 Create deploy-activity.yml
  .github/workflows/deploy-activity.yml
Labels: backend, chore

#56 chore: entity 생성
  activity/src/main/java/life/eventory/activity/entity/ActivityEntity.java
Labels: backend, chore

#58 fix: 워크플로우 수정 테스트
  activity/src/main/java/life/eventory/activity/entity/ActivityEntity.java
Labels: fix, backend

#59 chore: 활동 서버 요청 라우트 추가
  gateway/src/main/resources/application.properties
Labels: backend, chore

#60 Chore: 활동 서버 요청 라우트 추가
  gateway/src/main/resources/application.properties
Labels: backend, chore

#61 fix: 활동 서버 요청 라우트 번호 수정
  gateway/src/main/resources/application.properties
Labels: fix, backend

#62 chore: user 기본 구조 생성
  user/src/main/java/life/eventory/user/controller/UserController.java
  user/src/main/java/life/eventory/user/dto/UserDTO.java
  user/src/main/java/life/eventory/user/entity/UserEntity.java
  user/src/main/java/life/eventory/user/repository/UserRepository.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: backend, chore

#64 Create deploy-user.yml
  .github/workflows/deploy-user.yml
Labels: backend, chore

#66 chore: gateway user 서버 라우트 경로 추가
  gateway/src/main/resources/application.properties
Labels: backend, chore

#70 chore: image 용량 제한 100MB 확장
  gateway/src/main/resources/application.properties
  image/src/main/resources/application.properties
Labels: backend, chore

#71 fix: image 응답 DTO 예시값 변경
  image/src/main/java/life/eventory/image/dto/ResponseDTO.java
Labels: fix, backend, docs

#72 refactor: image 컨트롤러 분리, 및 액추에이터 설정
  image/build.gradle
  image/src/main/java/life/eventory/image/controller/ImageApi.java
  image/src/main/java/life/eventory/image/controller/ImageController.java
  image/src/main/java/life/eventory/image/dto/ResponseDTO.java
  image/src/main/java/life/eventory/image/dto/ReturnDTO.java
  image/src/main/java/life/eventory/image/service/ImageService.java
  image/src/main/java/life/eventory/image/service/impl/ImageServiceImpl.java
  image/src/main/resources/application.properties
Labels: refactor, backend

#75 fix: event, image 워크플로우 헬스체크 수정
  .github/workflows/deploy-event.yml
  .github/workflows/deploy-image.yml
  image/src/main/java/life/eventory/image/dto/ReturnDTO.java
Labels: fix, backend

#76 docs: image 반환 예시값 수정
  image/src/main/java/life/eventory/image/dto/ReturnDTO.java
Labels: refactor, backend

#80 feat: image 삭제 기능 구현
  image/src/main/java/life/eventory/image/controller/ImageApi.java
  image/src/main/java/life/eventory/image/controller/ImageController.java
  image/src/main/java/life/eventory/image/service/ImageService.java
  image/src/main/java/life/eventory/image/service/impl/ImageServiceImpl.java
Labels: feature, backend

#81 refactor: image 삭제 로직 수정
  image/src/main/java/life/eventory/image/controller/ImageApi.java
  image/src/main/java/life/eventory/image/controller/ImageController.java
  image/src/main/java/life/eventory/image/service/impl/ImageServiceImpl.java
Labels: refactor, backend

#82 feat: 회원가입 구현
  user/src/main/java/life/eventory/user/controller/UserController.java
  user/src/main/java/life/eventory/user/dto/UserDTO.java
  user/src/main/java/life/eventory/user/dto/UserSignUpRequest.java
  user/src/main/java/life/eventory/user/entity/UserEntity.java
  user/src/main/java/life/eventory/user/repository/UserRepository.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: feature, backend

#88 refactor: image 업로드 어노테이션 변경
  image/src/main/java/life/eventory/image/controller/ImageApi.java
  image/src/main/java/life/eventory/image/controller/ImageController.java
Labels: refactor, backend

#89 refactor: 행사 업로드 과정 리팩토링
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/dto/CreateEventRequest.java
  event/src/main/java/life/eventory/event/dto/NewEventDTO.java
  event/src/main/java/life/eventory/event/service/CommunicationService.java
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: refactor, backend

#90 docs: 행사 업로드 스웨거 요청 타입 명시
  event/src/main/java/life/eventory/event/controller/EventController.java
Labels: backend, docs

#91 feat: 내 동네 설정
  user/build.gradle
  user/src/main/java/life/eventory/user/config/AppConfig.java
  user/src/main/java/life/eventory/user/config/SecurityConfig.java
  user/src/main/java/life/eventory/user/config/SwaggerConfig.java
  user/src/main/java/life/eventory/user/controller/UserController.java
  user/src/main/java/life/eventory/user/dto/UserLocationRequest.java
  user/src/main/java/life/eventory/user/dto/UserSignUpRequest.java
  user/src/main/java/life/eventory/user/dto/UserUpdateRequest.java
  user/src/main/java/life/eventory/user/entity/UserEntity.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
  user/src/main/resources/application.properties
Labels: feature, backend

#93 docs: 행사 업로드 스웨거 요청 타입 인코드
  event/src/main/java/life/eventory/event/config/SwaggerConfig.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
Labels: backend, docs

#97 fix: gateway cors 수정
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
Labels: fix, backend

#99 feat: event 행사 수정 기능 추가
  event/src/main/java/life/eventory/event/controller/EventApi.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/dto/UpdateEventRequest.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: feature, backend

#100 feat: event 행사 수정 기능 수정
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: fix, backend

#101 fix: event 시큐리티 cors 수정
  event/src/main/java/life/eventory/event/config/SecurityConfig.java
  image/src/main/java/life/eventory/image/config/SecurityConfig.java
Labels: fix, backend

#104 feat: Event 해시태그 및 이미지 업로드 로직 개선
  event/src/main/java/life/eventory/event/EventApplication.java
  event/src/main/java/life/eventory/event/dto/EventDTO.java
  event/src/main/java/life/eventory/event/dto/NewEventDTO.java
  event/src/main/java/life/eventory/event/entity/Event.java
  event/src/main/java/life/eventory/event/entity/Tag.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/repository/TagRepository.java
  event/src/main/java/life/eventory/event/service/EventTagService.java
  event/src/main/java/life/eventory/event/service/TagNormalizer.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
  event/src/main/java/life/eventory/event/service/impl/EventTagServiceImpl.java
  event/src/main/resources/application.properties
Labels: feature, backend

#106 fix: findByHistory 구문 파싱 실패 오류 수정 - 쿼리 작성
  activity/src/main/java/life/eventory/activity/repository/HistoryRepository.java
Labels: fix, backend

#108 feat: 전체 행사 조회 기능 추가
  event/src/main/java/life/eventory/event/config/SwaggerConfig.java
  event/src/main/java/life/eventory/event/controller/EventApi.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: fix, backend

#110 feat: 행사 거리순 조회 기능 추가 및 마감일 로직 추가
  event/src/main/java/life/eventory/event/controller/EventApi.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/dto/LocationDTO.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: feature, backend

#109 feat: signup 이미지 업로드 기능 추가
  user/build.gradle
  user/src/main/java/life/eventory/user/config/AppConfig.java
  user/src/main/java/life/eventory/user/config/SecurityConfig.java
  user/src/main/java/life/eventory/user/config/SwaggerConfig.java
  user/src/main/java/life/eventory/user/controller/UserController.java
  user/src/main/java/life/eventory/user/dto/MultipartFileResource.java
  user/src/main/java/life/eventory/user/dto/UserSignUpRequest.java
  user/src/main/java/life/eventory/user/entity/UserEntity.java
  user/src/main/java/life/eventory/user/service/CommunicationService.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/CommunicationServiceImpl.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: feature, backend

#115 refactor: event 행사 생성 유저 확인 로직 추가
  event/src/main/java/life/eventory/event/dto/LocationDTO.java
  event/src/main/java/life/eventory/event/service/CommunicationService.java
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: refactor, backend

#117 fix: gateway security 설정 변경
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
Labels: fix, backend

#121 refactor: event 행사 확인 경로 user와 통일
  event/src/main/java/life/eventory/event/controller/EventApi.java
Labels: refactor, backend

#122 chore: ai init
  .github/workflows/deploy-ai.yml
  ai/.gitattributes
  ai/.gitignore
  ai/build.gradle
  ai/gradle/wrapper/gradle-wrapper.jar
  ai/gradle/wrapper/gradle-wrapper.properties
  ai/gradlew
  ai/gradlew.bat
  ai/settings.gradle
  ai/src/main/java/life/eventory/ai/AiApplication.java
  ai/src/main/java/life/eventory/ai/config/AppConfig.java
  ai/src/main/java/life/eventory/ai/config/SecurityConfig.java
  ai/src/main/java/life/eventory/ai/config/SwaggerConfig.java
  ai/src/main/resources/application.properties
  ai/src/test/java/life/eventory/ai/AiApplicationTests.java
  gateway/src/main/resources/application.properties
Labels: backend, chore

#125 feat: event 행사 단건 조회 기능 추가
  event/src/main/java/life/eventory/event/controller/EventApi.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: feature, backend

#126 feat: ai 행사 생성, 행사 요약 생성 기능 구현
  aggregator/src/main/java/life/eventory/aggregator/config/SwaggerConfigRefreshInterceptor.java
  ai/build.gradle
  ai/src/main/java/life/eventory/ai/AiApplication.java
  ai/src/main/java/life/eventory/ai/controller/AiApi.java
  ai/src/main/java/life/eventory/ai/controller/AiController.java
  ai/src/main/java/life/eventory/ai/dto/AiEventDTO.java
  ai/src/main/java/life/eventory/ai/dto/EventDTO.java
  ai/src/main/java/life/eventory/ai/service/AiService.java
  ai/src/main/java/life/eventory/ai/service/CommunicationService.java
  ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
  ai/src/main/java/life/eventory/ai/service/impl/CommunicationServiceImpl.java
  ai/src/main/resources/application.properties
Labels: feature, backend

#128 fix: event 행사 AI 생성 스웨거 문서 수정
  event/src/main/java/life/eventory/event/controller/EventApi.java
Labels: fix, backend

#129 fix: 해시태그 생성 # 기호 제외
  ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
Labels: fix, backend

#124 fix: 사용자 히스토리 목록 조회 수정
  activity/src/main/java/life/eventory/activity/controller/HistoryController.java
Labels: fix, backend

#131 feat: event 외부 행사 정보 조회 및 내부 DB 통합 기능 구현
  event/build.gradle
  event/src/main/java/life/eventory/event/EventApplication.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/controller/QrController.java
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/controller/api/QrApi.java
  event/src/main/java/life/eventory/event/dto/external/ConvertAddress.java
  event/src/main/java/life/eventory/event/dto/external/DaeguEventDTO.java
  event/src/main/java/life/eventory/event/entity/Event.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/ExternalEventInfoAggregator.java
  event/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  event/src/main/resources/application.properties
Labels: feature, backend

#134 fix: event 주소 검색 대구 컴포넌트 추가
  event/src/main/java/life/eventory/event/service/ExternalEventInfoAggregator.java
Labels: fix, backend

#133 feat : user 정보 업데이트 기능 수정
  user/src/main/java/life/eventory/user/controller/UserAPI.java
  user/src/main/java/life/eventory/user/controller/UserController.java
  user/src/main/java/life/eventory/user/dto/UserUpdateRequest.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: feature, backend

#135 refactor: event 주최자 ID로 조회 페이징 처리
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: refactor, backend

#136 feat: event 주최자 존재 여부 확인 기능 추가
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: feature, backend

#139 feat: event QR 발급, 조회 기능 구현
  event/src/main/java/life/eventory/event/controller/QrController.java
  event/src/main/java/life/eventory/event/controller/api/QrApi.java
  event/src/main/java/life/eventory/event/dto/EventDTO.java
  event/src/main/java/life/eventory/event/entity/Event.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/InMemoryMultipartFile.java
  event/src/main/java/life/eventory/event/service/QrService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
  event/src/main/java/life/eventory/event/service/impl/QrServiceImpl.java
  event/src/main/resources/application.properties
Labels: feature, backend

#140 feat: JWT 토큰 발급
  user/build.gradle
  user/src/main/java/life/eventory/user/config/AuthConfig.java
  user/src/main/java/life/eventory/user/controller/JwksController.java
  user/src/main/java/life/eventory/user/service/TokenService.java
  user/src/main/java/life/eventory/user/service/impl/TokenServiceImpl.java
Labels: feature, backend

#141 feat: user 로그인, 토큰 재발급 기능 작동 확인
  user/src/main/java/life/eventory/user/config/AuthConfig.java
  user/src/main/java/life/eventory/user/controller/UserController.java
  user/src/main/java/life/eventory/user/controller/api/UserAPI.java
  user/src/main/java/life/eventory/user/dto/login/LoginRequest.java
  user/src/main/java/life/eventory/user/dto/login/LoginResponse.java
  user/src/main/java/life/eventory/user/service/TokenService.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/TokenServiceImpl.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
  user/src/main/resources/application.properties
Labels: feature, backend

#142 feat: 토큰 검증 로직 추가, 타 서버 스웨거 수정
  activity/src/main/java/life/eventory/activity/config/SwaggerConfig.java
  ai/src/main/java/life/eventory/ai/config/SwaggerConfig.java
  event/src/main/java/life/eventory/event/config/SwaggerConfig.java
  gateway/build.gradle
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
  gateway/src/main/java/life/eventory/gateway/filter/UserPropagationFilter.java
  image/src/main/java/life/eventory/image/config/SwaggerConfig.java
  user/src/main/java/life/eventory/user/config/SwaggerConfig.java
Labels: feature, backend

#143 refactor: user 로그인 반환값 수정
  user/src/main/java/life/eventory/user/controller/UserController.java
  user/src/main/java/life/eventory/user/dto/login/LoginResponse.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/TokenServiceImpl.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: refactor, backend

#144 refactor: 행사 생성 임시 개방
  gateway/src/main/java/life/eventory/gateway/config/SecurityConfig.java
Labels: refactor, backend

#157 refactor: event 행사 조회, AI 요약 생성 시 히스토리 생성
  ai/src/main/java/life/eventory/ai/controller/AiApi.java
  ai/src/main/java/life/eventory/ai/controller/AiController.java
  ai/src/main/java/life/eventory/ai/dto/activity/HistoryRequest.java
  ai/src/main/java/life/eventory/ai/dto/activity/HistoryResponse.java
  ai/src/main/java/life/eventory/ai/service/AiService.java
  ai/src/main/java/life/eventory/ai/service/CommunicationService.java
  ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
  ai/src/main/java/life/eventory/ai/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/dto/activity/HistoryRequest.java
  event/src/main/java/life/eventory/event/dto/activity/HistoryResponse.java
  event/src/main/java/life/eventory/event/service/CommunicationService.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: refactor, backend

#162 feat: event 행사 리스트 해시태그 조회 기능 추가
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/entity/Event.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: feature, backend

#164 feat: event 행사 추천 API 구현
  ai/src/main/java/life/eventory/ai/controller/AiApi.java
  ai/src/main/java/life/eventory/ai/controller/AiController.java
  ai/src/main/java/life/eventory/ai/dto/Recommender.java
  ai/src/main/java/life/eventory/ai/service/AiEventRecommender.java
  ai/src/main/java/life/eventory/ai/service/AiService.java
  ai/src/main/java/life/eventory/ai/service/CommunicationService.java
  ai/src/main/java/life/eventory/ai/service/impl/AiEventRecommenderImpl.java
  ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
  ai/src/main/java/life/eventory/ai/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/dto/activity/BookmarkResponse.java
  event/src/main/java/life/eventory/event/dto/activity/ParticipationResponse.java
  event/src/main/java/life/eventory/event/dto/recommender/AiRecommendResponse.java
  event/src/main/java/life/eventory/event/dto/recommender/Recommender.java
  event/src/main/java/life/eventory/event/repository/EventRepository.java
  event/src/main/java/life/eventory/event/service/CommunicationService.java
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/service/recommender/EventRecommender.java
  event/src/main/java/life/eventory/event/service/recommender/EventRecommenderImpl.java
Labels: feature, backend

#165 feat: event 행사 추천 API 엔드포인트 수정
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
Labels: fix, backend

#169 feature: 참여 행사 리뷰 관련 기능 구현
  activity/src/main/java/life/eventory/activity/controller/ReviewController.java
  activity/src/main/java/life/eventory/activity/controller/api/ReviewAPI.java
  activity/src/main/java/life/eventory/activity/dto/review/ReviewRequestDTO.java
  activity/src/main/java/life/eventory/activity/dto/review/ReviewResponseDTO.java
  activity/src/main/java/life/eventory/activity/entity/ReviewEntity.java
  activity/src/main/java/life/eventory/activity/repository/ParticipationRepository.java
  activity/src/main/java/life/eventory/activity/repository/ReviewRepository.java
  activity/src/main/java/life/eventory/activity/service/ReviewService.java
  activity/src/main/java/life/eventory/activity/service/impl/ReviewServiceImpl.java
Labels: feature, backend

#170 feature: 행사 북마크 한 횟수 조회 기능 추가
  activity/src/main/java/life/eventory/activity/controller/BookmarkController.java
  activity/src/main/java/life/eventory/activity/controller/api/BookmarkAPI.java
  activity/src/main/java/life/eventory/activity/dto/bookmark/BookmarkResponseDTO.java
  activity/src/main/java/life/eventory/activity/entity/BookmarkEntity.java
  activity/src/main/java/life/eventory/activity/repository/BookmarkRepository.java
  activity/src/main/java/life/eventory/activity/service/BookmarkService.java
  activity/src/main/java/life/eventory/activity/service/impl/BookmarkServiceImpl.java
Labels: feature, backend

#171 feat : 구독 목록 기능 반환값 수정
  user/src/main/java/life/eventory/user/controller/SubscriptionController.java
  user/src/main/java/life/eventory/user/controller/api/SubscriptionAPI.java
  user/src/main/java/life/eventory/user/dto/SubscriptionListResponse.java
  user/src/main/java/life/eventory/user/entity/SubscriptionEntity.java
  user/src/main/java/life/eventory/user/entity/UserEntity.java
  user/src/main/java/life/eventory/user/service/CommunicationService.java
  user/src/main/java/life/eventory/user/service/SubscriptionService.java
  user/src/main/java/life/eventory/user/service/impl/CommunicationServiceImpl.java
  user/src/main/java/life/eventory/user/service/impl/SubscriptionServiceImpl.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: feature, backend

#173 refactor: user 사용자 정보 수정 이미지 삭제 로직 추가
  event/src/main/java/life/eventory/event/controller/EventController.java
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/service/EventService.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
  user/src/main/java/life/eventory/user/dto/UserUpdateRequest.java
  user/src/main/java/life/eventory/user/service/CommunicationService.java
  user/src/main/java/life/eventory/user/service/impl/CommunicationServiceImpl.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: refactor, backend

#187 refactor: 행사 요약 생성 프롬프트 수정
  ai/src/main/java/life/eventory/ai/service/impl/AiServiceImpl.java
Labels: refactor, backend

#194 refactor: 스웨거 문구 수정 및 메일 설정 환경변수로 변경
  user/src/main/java/life/eventory/user/controller/api/UserAPI.java
  user/src/main/java/life/eventory/user/service/impl/EmailServiceImpl.java
  user/src/main/resources/application.properties
Labels: refactor, backend

#196 fix: event 행사 추천 코멘트 HTTP 메소드 수정 및 행사 수정 오류 수정
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
  event/src/main/java/life/eventory/event/service/impl/EventServiceImpl.java
Labels: fix, backend

#197 fix: event 행사 추천 코멘트 쿼리 파라미터 수정
  event/src/main/java/life/eventory/event/service/impl/CommunicationServiceImpl.java
Labels: fix, backend

#202 refactor: event AI 추천 행사 멘트 수정
  event/src/main/java/life/eventory/event/controller/api/EventApi.java
  event/src/main/java/life/eventory/event/service/recommender/EventRecommenderImpl.java
Labels: refactor, backend

#213 refactor: API 엔드포인트 오타 수정
  activity/src/main/java/life/eventory/activity/service/impl/ReviewServiceImpl.java
Labels: refactor, backend

#215 refactor: 스웨거 수정
  activity/src/main/java/life/eventory/activity/controller/api/ReviewAPI.java
Labels: refactor, backend

#222 refactor: 이메일 전송 수정
  user/src/main/java/life/eventory/user/controller/EmailController.java
  user/src/main/java/life/eventory/user/service/UserService.java
  user/src/main/java/life/eventory/user/service/impl/UserServiceImpl.java
Labels: refactor, backend
